### ISSUE TITLE
Release version?

### ISSUE THREAD

**Issue by chjohnst** [jamesdbrock/hffix#14]
I am building an RPM to easily distribute this across my devs systems/containers, are you ever going to do a versioned release?

**Comment by jamesdbrock** [comment]
I'll do a 1.0.0 version release now. 

Do you have any suggestions or requests for how to do the versioning that makes it easy for you to build RPMs? Is annotated git tags with SemVer okay? Do you think there should be an rpm .spec file in the repository?

**Comment by jamesdbrock** [comment]
On reflection, maybe versioned releases aren't worth it. This library is pretty stable, and I doubt there will ever be reason to make big breaking changes which would be signaled by a major version bump. I think in the age of Github it's more natural to pin dependencies by git commit hash. I'm willing to be convinced otherwise, but for now I'm going to close this issue.
